name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101        
    - name: Checkout lmdb
      uses: actions/checkout@v2
      with:
        repository: LMDB/lmdb
        ref: mdb.master
        path: lmdb
    - name: Build lmdb
      working-directory: ${{ runner.workspace }}/lunr-core/lmdb/libraries/liblmdb/
      run: make
    - name: Install dependencies
      run: dotnet restore      
    - name: Build
      run: dotnet build --configuration Release --no-restore      
    - name: Test
      run: LD_LIBRARY_PATH=${{ runner.workspace }}/lunr-core/lmdb/libraries/liblmdb/:$LD_LIBRARY_PATH dotnet test --no-restore --verbosity normal
